export enum VerificationType {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION_TOKEN',
  PHONE_VERIFICATION = 'PHONE_VERIFICATION_OTP',
  PASSWORD_RESET_TOKEN = 'PASSWORD_RESET_TOKEN',
  PASSWORD_RESET_OTP = 'PASSWORD_RESET_OTP',
}
