export enum VerificationType {
  USER_REGISTRATION_VERIFICATION = 'REGISTRATION_VERIFICATION_TOKEN',
  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
  PASSWORD_RESET_TOKEN = 'PASSWORD_RESET_TOKEN',
  PASSWORD_RESET_OTP = 'PASSWORD_RESET_OTP',
}
