export enum ActivityType {
  // User-related activities
  USER_REGISTER = 'USER_REGISTER',
  USER_REGISTER_VERIFICATION = 'USER_REGISTER_VERIFICATION',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE',
  USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
  USER_DELETE_ACCOUNT = 'USER_DELETE_ACCOUNT',
  REQUEST_OTP = 'REQUEST_OTP',
  REQUEST_TOKEN = 'REQUEST_TOKEN',
  USER_VERIFY_PHONE = 'USER_VERIFY_PHONE',

  // Review-related activities
  REVIEW_ADD = 'REVIEW_ADD',
  REVIEW_UPDATE = 'REVIEW_UPDATE',
  REVIEW_DELETE = 'REVIEW_DELETE',

  //Admin-related activities
  ADMIN_UPDATE_USER_ROLE = 'ADMIN_UPDATE_USER_ROLE',
  ADMIN_DELETE_USER = 'ADMIN_DELETE_USER',
  ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER',
  ADMIN_UPDATE_PRODUCT = 'ADMIN_UPDATE_PRODUCT',
  ADMIN_DELETE_PRODUCT = 'ADMIN_DELETE_PRODUCT',
  ADMIN_ADD_PRODUCT = 'ADMIN_ADD_PRODUCT',
  ADMIN_UPDATE_ORDER_STATUS = 'ADMIN_UPDATE_ORDER_STATUS',

  //Check functionality
  CHECK_CREATE = 'CHECK_CREATE',
}
