export enum ActivityType {
  // User-related activities
  USER_REGISTER = 'USER_REGISTER',
  USER_REGISTER_VERIFICATION = 'USER_REGISTER_VERIFICATION',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGIN_GOOGLEOAUTH = 'USER_LOGIN_GOOGLEOAUTH',
  USER_LOGIN_FACE = 'USER_LOGIN_FACE',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE',
  USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
  USER_RESET_PASSWORD_BY_EMAIL_TOKEN = 'USER_RESET_PASSWORD_BY_EMAIL_TOKEN',
  USER_RESET_PASSWORD_BY_SMS_OTP = 'USER_RESET_PASSWORD_BY_SMS_OTP',
  USER_DELETE_ACCOUNT = 'USER_DELETE_ACCOUNT',
  REQUEST_OTP = 'REQUEST_OTP',
  REQUEST_TOKEN = 'REQUEST_TOKEN',
  USER_VERIFY_PHONE = 'USER_VERIFY_PHONE',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  USER_VERIFY_FACE = 'USER_VERIFY_FACE',

  // Review-related activities
  REVIEW_ADD = 'REVIEW_ADD',
  REVIEW_UPDATE = 'REVIEW_UPDATE',
  REVIEW_DELETE = 'REVIEW_DELETE',

  //Admin-related activities
  ADMIN_UPDATE_USER_ROLE = 'ADMIN_UPDATE_USER_ROLE',
  ADMIN_DELETE_USER = 'ADMIN_DELETE_USER',
  ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER',
  ADMIN_UPDATE_PRODUCT = 'ADMIN_UPDATE_PRODUCT',
  ADMIN_DELETE_PRODUCT = 'ADMIN_DELETE_PRODUCT',
  ADMIN_ADD_PRODUCT = 'ADMIN_ADD_PRODUCT',
  ADMIN_UPDATE_ORDER_STATUS = 'ADMIN_UPDATE_ORDER_STATUS',

  //Check functionality
  CHECK_CREATE = 'CHECK_CREATE',

  // Subscription-related activities
  SUBSCRIPTION1M = 'SUBSCRIPTION_1M',
  SUBSCRIPTION6M = 'SUBSCRIPTION_6M',
  SUBSCRIPTION12M = 'SUBSCRIPTION_12M',
  SUBSCRIPTION_CANCEL = 'SUBSCRIPTION_CANCEL',

  // Payment-related activities
  PAYMENT1M = 'PAYMENT_FOR_1M_SUBSCRIPTION',
  PAYMENT6M = 'PAYMENT_FOR_6M_SUBSCRIPTION',
  PAYMENT12M = 'PAYMENT_FOR_12M_SUBSCRIPTION',

  // OCR-related activities
  OCR_EXTRACT_TEXT_FROM_PDF = 'OCR_EXTRACT_TEXT_FROM_PDF',
  OCR_EXTRACT_TEXT_FROM_IMAGE = 'OCR_EXTRACT_TEXT_FROM_IMAGE',
  RESIZE_IMAGE = 'RESIZE_IMAGE',
  REMOVE_BACKGROUND = 'REMOVE_BACKGROUND',
  EDIT_IMAGE = 'EDIT_IMAGE',
}
